from django.db import models
from django.utils.encoding import smart_unicode

# Create your models here.
class SighUp(models.Model):
    first_name = models.CharField(max_length=120, null=True, blank=True)
    last_name = models.CharField(max_length=120, null=True, blank=True)
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __unicode__(self):
        return smart_unicode(self.email)
    
class Patient(models.Model):
    ivhun_type = models.CharField(max_length=120)
    full_name = models.CharField(max_length=120)
    patient_id = models.CharField(max_length=10)
    date_of_birth = models.DateField()
    address = models.CharField(max_length=200)
    father_phone = models.CharField(max_length=10)
    mother_phone = models.CharField(max_length=10)
    grade = models.CharField(max_length=2)
    educational_instatute = models.CharField(max_length=100)
    relevant_background = models.TextField()
    overall = models.TextField()
    thinking_skills = models.TextField()
    verbal_thinking_general = models.IntegerField()
    verbal_thinking_conclusion = models.IntegerField()
    verbal_thinking_gizra_shava = models.IntegerField()
    verbal_thinking_pitgamim = models.IntegerField()
    verbal_thinking_sivug = models.IntegerField()
    verbal_thinking_miyun = models.IntegerField()
    verbal_thinking_hagdara = models.IntegerField()
    verbal_thinking_mahutiyut = models.IntegerField()
    verbal_thinking_nirdfot = models.IntegerField()
    verbal_thinking_nigudim = models.IntegerField()
    yeda_ortography_general = models.TextField()
    yeda_ortography_kriat_milim_beheksher_diyuk = models.TextField()
    yeda_ortography_kriat_milim_bodedot_diyuk = models.TextField()
    yeda_ortography_kriat_milot_tefel_diyuk = models.TextField()
    yeda_ortography_kriat_itzurim_vetnuot_diyuk = models.TextField()
    yeda_ortography_kriat_milim_beheksher_ketzev = models.TextField()
    yeda_ortography_kriat_milim_bodedot_ketzev = models.TextField()
    yeda_ortography_kriat_milot_tefel_ketzev = models.TextField()
    yeda_ortography_kriat_itzurim_vetnuot_ketzev = models.TextField()
    havanat_hanishma = models.TextField()
    haarahat_kosher_ktiva = models.TextField()
    mudaut_fonologit = models.TextField()
    ran_test = models.TextField()
    shetef_miluli = models.TextField()
    eranut_morpho_tahbirit = models.TextField()
    eranut_tahbirit = models.TextField()
    kidron = models.TextField()
    rey = models.TextField()
    tifkudim_nihuliyim_hazutiim_merhaviim = models.TextField()
    shlifa_mehazikaron = models.TextField()
    yahalom = models.TextField()
    five_nine_two = models.TextField()
    conclusion = models.TextField()
    hamlatzot = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __unicode__(self):
        return smart_unicode(self.date_of_birth)